function appendTableComponent(obj)

testTime = datestr(obj.time,'hh:MM:ss');
testDate = datestr(obj.time,'DD.mm.YYYY');

newRow = {obj.boardNumber,obj.deviceType,...
    obj.designation,obj.serialNumber,...
    obj.nameCriteria1,obj.valueCriteria1,...
    obj.nameCriteria2,obj.valueCriteria2,...
    obj.comment,testTime,...
    testDate,obj.inspectorName};

writecell(newRow,obj.tableComponent,'Sheet','Sample',...
    'WriteMode','append','AutoFitWidth',false);

end