function easterEgg
fprintf([...
    ',__,.........,__,......╭¬¬¬¬¬¬¬╮\n',...
    '`•.,¸,.•*¯`•.,¸,.•*|:¬¬¬¬¬¬::::|:^-----^ \n',...
    '`•.,¸,.•*¯`•.,¸,.•*|:¬¬¬¬¬¬::::||｡◕‿‿◕｡| \n',...
    '-........--""-.......--"╰O━━━━O╯╰--O-O--╯\n',...
    'Migrations completed\n',...
'Now you can run any script you want.\n',...
'Use mainApp variable to manage objects you connected in The Great Uniter.\n'...
]);
end